---
groups:
  - name: certify-vsphere
    jobs:
      - bats-centos
      - bats-ubuntu
      - test-stemcell
      - test-upgrade
      - certify-centos
      - certify-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/prepare-director.yml
    params: &prepare-director-params
      INFRASTRUCTURE:     vsphere
      DIRECTOR_VARS_FILE: {{vsphere_director_vars_file}}
      OPTIONAL_OPS_FILE:  |
        -o bosh-deployment/vsphere/resource-pool.yml
        -o pipelines/shared/assets/ops/remove-hm.yml

  - &prepare-director-ipv6
    task: prepare-director-ipv6
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/prepare-director.yml
    params:
      INFRASTRUCTURE:     vsphere
      DIRECTOR_VARS_FILE: {{vsphere_director_vars_file}}
      OPTIONAL_OPS_FILE:  |
        -o bosh-deployment/vsphere/resource-pool.yml
        -o pipelines/shared/assets/ops/remove-hm.yml
        -o bosh-deployment/misc/ipv6/bosh.yml
        -o bosh-linux-stemcell-builder/ci/assets/ipv6-director.yml
        -o bosh-deployment/misc/second-network.yml
        -o bosh-deployment/vsphere/second-network.yml

  - &deploy-director
    task: deploy-director
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/deploy-director.yml
    params:
      NETWORK_NAME: default

  - &run-bats
    task: run-bats
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/run-bats.yml
    params: &run-bats-params
      INFRASTRUCTURE:     vsphere
      BAT_INFRASTRUCTURE: vsphere
      BAT_NETWORKING:     manual
      BAT_RSPEC_FLAGS:    "--tag ~vip_networking --tag ~dynamic_networking --tag ~root_partition --tag ~raw_ephemeral_storage"

  - &test-stemcell
    task: test-stemcell
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/test-stemcell.yml
    params:
      BOSH_os_name: ubuntu-trusty
      package: ipv4director

  - &update-cloud-config
    task: update-cloud-config
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/update-cloud-config.yml
    params: &update-cloud-config-params
      INFRASTRUCTURE: vsphere
      DIRECTOR_VARS_FILE: {{vsphere_director_vars_file}}

  - &teardown
    task: teardown
    tags: [vsphere-v6.5]
    file: pipelines/shared/tasks/teardown.yml

jobs:
  - name: test-stemcell
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    tags: [vsphere-v6.5], trigger: true}
        - {get: cpi-release,     tags: [vsphere-v6.5], trigger: true}
        - {get: stemcell,        tags: [vsphere-v6.5], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,  tags: [vsphere-v6.5], trigger: true}
        - {get: pipelines,       tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-cli,        tags: [vsphere-v6.5], trigger: false}
        - {get: bats,            tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-deployment, tags: [vsphere-v6.5], trigger: false}
        - {get: syslog-release,  tags: [vsphere-v6.5], trigger: false}
        - {get: os-conf-release, tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-linux-stemcell-builder, tags: [vsphere-v6.5], trigger: false}
      - aggregate:
        - do:
          - {put: environment, tags: [vsphere-v6.5], params: {acquire: true}}
          - <<: *prepare-director
          - do:
              - <<: *deploy-director
              - <<: *update-cloud-config
              - <<: *test-stemcell
            ensure:
              do:
                - <<: *teardown
                - {put: environment, tags: [vsphere-v6.5], params: {release: environment}}
        # TODO(cdutra,lsantos): We don't have ipv6 configured on vsphere yet
        # - do:
        #   - {put: environment, tags: [vsphere-v6.5], params: {acquire: true}}
        #   - <<: *prepare-director-ipv6
        #   - do:
        #       - <<: *deploy-director
        #       - <<: *update-cloud-config
        #         params:
        #           <<: *update-cloud-config-params
        #           OPTIONAL_OPS_FILE: |
        #             -o pipelines/vsphere/assets/ipv6-cc.yml
        #       - <<: *test-stemcell
        #     ensure:
        #       do:
        #         - <<: *teardown
        #         - {put: environment, tags: [vsphere-v6.5], params: {release: environment}}


  - name: bats-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    tags: [vsphere-v6.5], trigger: true}
        - {get: cpi-release,     tags: [vsphere-v6.5], trigger: true}
        - {get: stemcell,        tags: [vsphere-v6.5], trigger: true, resource: centos-stemcell}
        - {get: after-midnight,  tags: [vsphere-v6.5], trigger: true}
        - {get: pipelines,       tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-cli,        tags: [vsphere-v6.5], trigger: false}
        - {get: bats,            tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-deployment, tags: [vsphere-v6.5], trigger: false}
      - {put: environment, tags: [vsphere-v6.5], params: {acquire: true}}
      - <<: *prepare-director
      - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: bosh-vsphere-esxi-centos-7-go_agent
        ensure:
          do:
            - <<: *teardown
            - {put: environment, tags: [vsphere-v6.5], params: {release: environment}}

  - name: bats-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,    tags: [vsphere-v6.5], trigger: true}
        - {get: cpi-release,     tags: [vsphere-v6.5], trigger: true}
        - {get: stemcell,        tags: [vsphere-v6.5], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,  tags: [vsphere-v6.5], trigger: true}
        - {get: pipelines,       tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-cli,        tags: [vsphere-v6.5], trigger: false}
        - {get: bats,            tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-deployment, tags: [vsphere-v6.5], trigger: false}
      - {put: environment, tags: [vsphere-v6.5], params: {acquire: true}}
      - <<: *prepare-director
      - do:
          - <<: *deploy-director
          - <<: *run-bats
            params:
              <<: *run-bats-params
              STEMCELL_NAME: bosh-vsphere-esxi-ubuntu-trusty-go_agent
        ensure:
          do:
            - <<: *teardown
            - {put: environment, tags: [vsphere-v6.5], params: {release: environment}}

  - name: test-upgrade
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release,     tags: [vsphere-v6.5], trigger: true}
        - {get: cpi-release,      tags: [vsphere-v6.5], trigger: true}
        - {get: stemcell,         tags: [vsphere-v6.5], trigger: true, resource: ubuntu-stemcell}
        - {get: after-midnight,   tags: [vsphere-v6.5], trigger: true}
        - {get: pipelines,        tags: [vsphere-v6.5], trigger: false}
        - {get: bosh-cli,         tags: [vsphere-v6.5], trigger: false}
        - {get: centos-stemcell,  tags: [vsphere-v6.5], trigger: false} # pass-through
        - {get: old-stemcell,     tags: [vsphere-v6.5], trigger: false}
        - {get: old-bosh-release, tags: [vsphere-v6.5], trigger: false, version: {version: {{old_bosh_release_version}}}, resource: bosh-release}
        - {get: old-cpi-release,  tags: [vsphere-v6.5], trigger: false, version: {version: {{old_cpi_release_version}}},  resource: cpi-release}
        - {get: bosh-deployment,  tags: [vsphere-v6.5], trigger: false}
      - {put: environment, tags: [vsphere-v6.5], params: {acquire: true}}
      - <<: *prepare-director
        input_mapping:
          stemcell:     old-stemcell
          bosh-release: old-bosh-release
          cpi-release:  old-cpi-release
        params:
          <<: *prepare-director-params
          OPTIONAL_OPS_FILE: |
            -o pipelines/shared/assets/ops/redis.yml
            -o bosh-deployment/vsphere/resource-pool.yml
            -o pipelines/shared/assets/ops/remove-provider-cert.yml
      - do:
          - <<: *deploy-director
            input_mapping:
              stemcell:     old-stemcell
              bosh-release: old-bosh-release
              cpi-release:  old-cpi-release
          - <<: *update-cloud-config
          - task: create-deployment
            tags: [vsphere-v6.5]
            file: pipelines/shared/tasks/create-deployment.yml
            input_mapping:
              stemcell:                  old-stemcell
            params:
              VCENTER_NETWORK_NAME: {{VCENTER_NETWORK_NAME}}
              INFRASTRUCTURE:       vsphere
              STEMCELL_NAME:        bosh-vsphere-esxi-ubuntu-trusty-go_agent
          - <<: *prepare-director
          - task: test-upgrade
            tags: [vsphere-v6.5]
            file: pipelines/shared/tasks/test-upgrade.yml
            input_mapping:
              old-director-state: director-state
              new-director-config: director-config
            output_mapping:
              new-director-state: director-state
        ensure:
          do:
            - <<: *teardown
            - {put: environment, tags: [vsphere-v6.5], params: {release: environment}}

  - name: certify-centos
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v6.5], trigger: true, passed: [bats-centos]}
        - {get: cpi-release,  tags: [vsphere-v6.5], trigger: true, passed: [bats-centos]}
        - {get: stemcell,     tags: [vsphere-v6.5], trigger: true, passed: [bats-centos, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    tags: [vsphere-v6.5], trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v6.5]
        params:
          CPI_RELEASE_NAME: bosh-vsphere-cpi
          STEMCELL_NAME:    bosh-vsphere-esxi-centos-7-go_agent
      - {put: receipt, tags: [vsphere-v6.5], params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    serial: true
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v6.5], trigger: true, passed: [bats-ubuntu]}
        - {get: cpi-release,  tags: [vsphere-v6.5], trigger: true, passed: [bats-ubuntu]}
        - {get: stemcell,     tags: [vsphere-v6.5], trigger: true, passed: [bats-ubuntu, test-upgrade, test-stemcell], resource: ubuntu-stemcell}
        - {get: pipelines,    tags: [vsphere-v6.5], trigger: false}
      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v6.5]
        params:
          CPI_RELEASE_NAME: bosh-vsphere-cpi
          STEMCELL_NAME:    bosh-vsphere-esxi-ubuntu-trusty-go_agent
      - {put: receipt, tags: [vsphere-v6.5], params: {file: certification/*-receipt.json}}

resources:
  - name: after-midnight
    type: time
    source:
      start: 12:00 AM -0700
      stop: 2:00 AM -0700
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master
  - name: bosh-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-deployment
      branch: master
  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release
  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: gocli-bats
  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent
  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  - name: old-stemcell
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-stemcell-(3213)-vsphere-esxi-ubuntu-trusty-go_agent.tgz
      region_name: us-east-1
  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1
  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-(\d+)-receipt\.json
      region_name: us-east-1
  - name: environment
    type: pool
    source:
      pool: vsphere-6.0
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
  - name: bosh-linux-stemcell-builder
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-linux-stemcell-builder
      branch: master
  - name: syslog-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/syslog-release
  - name: os-conf-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/os-conf-release
