---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine
    tag: "latest"
inputs:
  - name: pipelines
outputs:
  - name: terraform-vars
run:
  path: pipelines/oracle/tasks/prepare-terraform-vars.sh

params:
  oracle_apikey:
